exports.infog = require("./infogathering.js")
exports.postexploit = require("./postexploitation.js")
exports.injection = require("./injection.js")
exports.tools = require("./tools.js")
exports.scripting = require("./scripting.js")
exports.linux = require("./linux.js")
exports.windows = require("./windows.js")
//exports.reverseShells = require("./reverseShells.js")
exports.networking = require('./networking.js')

